export const LEGACY_APPS = [
  {
    id: "nutriromi",
    name: "NutriROMI",
    href: "https://nutricionromi.vercel.app/",
    category: "Nutricion",
    description: "Demo de expediente clinico de nutricion desde el punto de vista del paciente.",
    access: ["pacientecarlos@gmail.com", "Nutri16702"],
  },
  {
    id: "romimente",
    name: "ROMImente",
    href: "https://romiai.info/",
    category: "Psicologia",
    description: "Expediente clinico de psicologia para visualizar el flujo del especialista.",
    access: ["doctor@demo.com", "demo1234"],
  },
  {
    id: "romi-tanatologia",
    name: "ROMI Tanatologia",
    href: "https://romiai.info/",
    category: "Psicologia",
    description: "Expediente clinico de tanatologia para acompanamiento y seguimiento.",
    access: ["paliativos@demo.com", "demo1234"],
  },
  {
    id: "laion",
    name: "LAION",
    href: "https://www.oncolatam.org/",
    category: "Educacion",
    description: "Programa de inteligencia artificial en oncologia para Latinoamerica.",
    access: ["medico.premium@laion.test", "admin@laion.test", "Password123!"],
  },
  {
    id: "luma",
    name: "LUMA by ROMI",
    href: "https://lumaderomi.com/",
    category: "Proyecto",
    description: "Agenda virtual para organizar atencion, recordatorios y seguimiento.",
  },
] as const;
